config/routes.rb
Rails.application.routes.draw do
  get 'homes/index'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :omniauth_callbacks_new_user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :omniauth_callbacks_destroy_user_session
  end
  resources :users
  get 'homes/my_repositories', to: 'homes#my_repositories', as: 'my_repositories'
  get 'homes/my_organizations', to: 'homes#my_organizations', as: 'my_organizations'
  root 'homes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index; end

  def my_repositories; end
  def my_organizations; end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'My Profile', current_user.git_profile_url %><p></p>
<%= link_to 'My Repositories', my_repositories_path, remote: true %><p></p>
<%= link_to 'My Organizations', my_organizations_path, remote: true %><p></p>
<p id='repos'>
</p>

app/views/homes/my_organizations.js.erb
$.ajax({
  type: "GET",
  url: "<%= current_user.organizations_url %>",
  dataType: 'json',
  success: function(responce) {
    console.log(responce);
    $('#repos').empty();
    $('#repos').append("<table border=2><tr id='test'><th>Organization name</th><th>Organization Profile</th><th>Location</th><th>Members</th></tr></table>");
    $.each(responce, function (key, value) {
      $("<tr id='tr'>").insertAfter('#test');
      $('#tr').append('<td>'+ value.login +'</td>');
      $('#tr').append("<td><a href=https://github.com/orgs/"+ value.login + " target='_blank'>Click here</a></td></tr>");
      $.ajax({
        type: "GET",
        url: value.url,
        dataType: 'json',
        success: function(respo){
          $('#tr').append('<td>'+ respo.location +'</td>');
          $.ajax({
            type: "GET",
            url: 'https://api.github.com/orgs/'+ respo.login+ '/members',
            dataType: 'json',
            success: function(res){
              $('#tr').append("<table border=2><tr id='test2'><th>Member name</th><th>Profile</th></tr></table>");
              $.each(res, function (key, value) {
                $("<tr id='tr2'>").insertAfter('#test2');
                $('#tr2').append('<td>'+ value.login +'</td>');
                $('#tr2').append("<td><a href="+ value.html_url + " target='_blank'>Click here</a></td></tr>");
              });
            }
          });
        }
      });
    });
  }
});

app/views/homes/my_repositories.js.erb
$.ajax({
  type: "GET",
  url: "<%= current_user.repos_url %>",
  dataType: 'json',
  success: function(responce) {
    $('#repos').empty();
    $('#repos').append("<table border=2><tr id='test'><th>Repository name</th><th>Language</th><th>Last Pushed</th><th>Last modified</th><th>Repository Url</th></tr></table>");
    $.each(responce, function (key, value) {
      $("<tr id='tr'>").insertAfter('#test');
      $('#tr').append('<td>'+ value.name +'</td>');
      $('#tr').append('<td>'+ value.language +'</td>');
      $('#tr').append('<td>'+ value.pushed_at +'</td>');
      $('#tr').append('<td>'+ value.updated_at +'</td>');
      $('#tr').append("<td><a href="+ value.svn_url + " target='_blank'>Click here</a></td></tr>");
    });
  }
});